In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Ushuaia,AR,2022-11-11 06:11:31,-54.8000,-68.3000,40.66,75,75,2.30
1,1,Busselton,AU,2022-11-11 06:15:36,-33.6500,115.3333,62.94,39,52,17.34
2,2,Pedernales,DO,2022-11-11 06:15:37,18.0384,-71.7440,78.40,77,0,2.91
3,3,Atuona,PF,2022-11-11 06:15:37,-9.8000,-139.0333,77.79,81,15,14.20
4,4,Butaritari,KI,2022-11-11 06:15:21,3.0707,172.7902,81.50,81,57,18.72

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Create a Maximum Temperature Heatmap

In [5]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [6]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [7]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Create a Percent Humidity Heatmap

In [10]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Create a Percent Cloudiness Heatmap

In [12]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights = clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Create a Wind Speed Heatmap

In [14]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights = wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [15]:
# 6.5.3, Get Vacation Criteria

In [16]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 95

In [17]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
2,2,Pedernales,DO,2022-11-11 06:15:37,18.0384,-71.7440,78.40,77,0,2.91
3,3,Atuona,PF,2022-11-11 06:15:37,-9.8000,-139.0333,77.79,81,15,14.20
4,4,Butaritari,KI,2022-11-11 06:15:21,3.0707,172.7902,81.50,81,57,18.72
5,5,Samarai,PG,2022-11-11 06:15:37,-10.6167,150.6667,82.22,73,25,12.08
7,7,Carutapera,BR,2022-11-11 06:15:38,-1.1950,-46.0200,76.33,89,32,5.79
12,12,Marawi,PH,2022-11-11 06:15:40,7.9986,124.2928,76.95,79,86,2.86
13,13,Salalah,OM,2022-11-11 06:15:40,17.0151,54.0924,84.29,54,0,4.61
15,15,Cockburn Town,TC,2022-11-11 06:15:41,21.4612,-71.1419,81.79,80,0,16.46
19,19,Saint-Louis,SN,2022-11-11 06:15:43,16.3333,-15.0000,77.38,16,13,8.61
20,20,Souillac,MU,2022-11-11 06:15:43,-20.5167,57.5167,80.98,65,40,8.05

In [18]:
preferred_cities_df.count()

City_ID       152
City          152
Country       151
Date          152
Lat           152
Lng           152
Max Temp      152
Humidity      152
Cloudiness    152
Wind Speed    152
dtype: int64

In [19]:
preferred_cities_df.dropna()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
2,2,Pedernales,DO,2022-11-11 06:15:37,18.0384,-71.7440,78.40,77,0,2.91
3,3,Atuona,PF,2022-11-11 06:15:37,-9.8000,-139.0333,77.79,81,15,14.20
4,4,Butaritari,KI,2022-11-11 06:15:21,3.0707,172.7902,81.50,81,57,18.72
5,5,Samarai,PG,2022-11-11 06:15:37,-10.6167,150.6667,82.22,73,25,12.08
7,7,Carutapera,BR,2022-11-11 06:15:38,-1.1950,-46.0200,76.33,89,32,5.79
...,...,...,...,...,...,...,...,...,...,...
543,543,Yining,CN,2022-11-11 06:30:03,29.0361,114.5636,84.20,45,21,3.13
546,546,Harper,LR,2022-11-11 06:30:05,4.3750,-7.7169,76.80,86,97,6.42
547,547,Mulanje,MW,2022-11-11 06:30:05,-16.0316,35.5000,83.46,53,99,3.20
549,549,Pedasi,PA,2022-11-11 06:30:06,7.5333,-80.0333,76.06,88,100,10.31
556,556,Maharajganj,IN,2022-11-11 06:31:09,27.1333,83.5667,81.57,40,0,7.40

In [20]:
preferred_cities_df["Country"].fillna("No Country", inplace = True)
preferred_cities_df

C:\Users\sebas\anaconda3\envs\PythonData\lib\site-packages\pandas\core\generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
2,2,Pedernales,DO,2022-11-11 06:15:37,18.0384,-71.7440,78.40,77,0,2.91
3,3,Atuona,PF,2022-11-11 06:15:37,-9.8000,-139.0333,77.79,81,15,14.20
4,4,Butaritari,KI,2022-11-11 06:15:21,3.0707,172.7902,81.50,81,57,18.72
5,5,Samarai,PG,2022-11-11 06:15:37,-10.6167,150.6667,82.22,73,25,12.08
7,7,Carutapera,BR,2022-11-11 06:15:38,-1.1950,-46.0200,76.33,89,32,5.79
...,...,...,...,...,...,...,...,...,...,...
543,543,Yining,CN,2022-11-11 06:30:03,29.0361,114.5636,84.20,45,21,3.13
546,546,Harper,LR,2022-11-11 06:30:05,4.3750,-7.7169,76.80,86,97,6.42
547,547,Mulanje,MW,2022-11-11 06:30:05,-16.0316,35.5000,83.46,53,99,3.20
549,549,Pedasi,PA,2022-11-11 06:30:06,7.5333,-80.0333,76.06,88,100,10.31
556,556,Maharajganj,IN,2022-11-11 06:31:09,27.1333,83.5667,81.57,40,0,7.40

In [21]:
preferred_cities_df.count()

City_ID       152
City          152
Country       152
Date          152
Lat           152
Lng           152
Max Temp      152
Humidity      152
Cloudiness    152
Wind Speed    152
dtype: int64

In [22]:
# 6.5.4, Map Vacation Criteria

In [23]:
# Get Travel Destinations
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

             City Country  Max Temp      Lat       Lng Hotel Name
2      Pedernales      DO     78.40  18.0384  -71.7440
3          Atuona      PF     77.79  -9.8000 -139.0333
4      Butaritari      KI     81.50   3.0707  172.7902
5         Samarai      PG     82.22 -10.6167  150.6667
7      Carutapera      BR     76.33  -1.1950  -46.0200
12         Marawi      PH     76.95   7.9986  124.2928
13        Salalah      OM     84.29  17.0151   54.0924
15  Cockburn Town      TC     81.79  21.4612  -71.1419
19    Saint-Louis      SN     77.38  16.3333  -15.0000
20       Souillac      MU     80.98 -20.5167   57.5167

In [24]:
# Retrieve Hotels from a Nearby Search
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [25]:
# Practice Using a Fixed Latitude and Longitude
# Dependencies and Setup
import requests
import gmaps

# Import API key
from config import g_key

In [26]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

hotels

{'html_attributions': [],
 'next_page_token': 'AW30NDwyf7e2FVuM6uMyF5RzEzKmjE3W4UhUGxnHDBr4kdzT8EpvZiu3wJ0c1XQF1HxUp4xXvpAPpOBCmkHP0WrQibngymzIwdqzQPSzXfwymMQr1_ALrf6xi67TqgPUeHlHW7bLHiVdVh_2w5djEIe2eaR1OrKDqywVGPHmc8j4jUyvP9AMYXTSAwCUxpJKuRsJwylcUqgJvpfIHPR-xXWW5A4-2L91H1myeJGYyEfOuH4hAhjnfxmtmWXu1SQMWTRoqQztHQX71BaucT1y_vFof2kZClOWa-7GM0iIeNh8ZEoGMIa5INI6xDUasHpFzT3_88omy3GzBlam2Aa6Fue_hjcjD25klzS_IR6657jxJY50HwHMTdXCvZxbDIRSOCcahhSWIdKlj7X7hkekltQIPBQEmdPVS1J2jhbLDalwPfLd-2R1LCQQYXs',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277},
    'viewport': {'northeast': {'lat': 48.8594360302915,
      'lng': 2.354355480291502},
     'southwest': {'lat': 48.8567380697085, 'lng': 2.351657519708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Duo',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">Hôtel Duo</a>'],
     'photo_reference': 'AW30NDxcwUWvLIh3vGy0GlHBHA3IcyJatoWA2jBf8sUe6qTyvWvP4R5K86qLYNZfWGe4jSpBnNTqb2bIK3rRYDNBFFSM8ygqsYK01O2apQmSSYceJE2c_gB6_KuN_Xtp9bAlpGIUBA2oknmNWvGQ37pm17cu3s0V49mX6xWnNrNgE2Br2y8G',
     'width': 5760}],
   'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'plus_code': {'compound_code': 'V953+65 Paris, France',
    'global_code': '8FW4V953+65'},
   'rating': 4.3,
   'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'scope': 'GOOGLE',
   'types': ['gym',
    'spa',
    'lodging',
    'night_club',
    'bar',
    'health',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 351,
   'vicinity': '11 Rue du Temple, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944},
    'viewport': {'northeast': {'lat': 48.8595483302915,
      'lng': 2.347785530291502},
     'southwest': {'lat': 48.8568503697085, 'lng': 2.345087569708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Britannique Hotel - Paris Centre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1426,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">Britannique Hotel - Paris Centre</a>'],
     'photo_reference': 'AW30NDxHGySBkAu1ZxOjDFVWzrQ2FzPr_MiVw3TeQODZBius-C26Cgiu0NUSbPbeXm_0YDIbzf9Q-oEid64WrTs0NuTfrhqF1ztWc1D1rHAHgQHaLSXebadwVWk0N8ALSWr7s8MNIJWvm3-pO1kdIs0fXueJxur7OoxFH-ZlmXF43QpQ-amu',
     'width': 1476}],
   'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'plus_code': {'compound_code': 'V85W+8H Paris, France',
    'global_code': '8FW4V85W+8H'},
   'rating': 4.7,
   'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 760,
   'vicinity': '20 Avenue Victoria, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8607013, 'lng': 2.3469937},
    'viewport': {'northeast': {'lat': 48.8617860302915,
      'lng': 2.347927730291502},
     'southwest': {'lat': 48.8590880697085, 'lng': 2.345229769708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Les Halles Paris',
   'photos': [{'height': 853,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Apart&#39;hotel Les Halles Paris</a>'],
     'photo_reference': 'AW30NDytzdqXmnAJj5NDUPcd299m8thlfZWGwyrsvlYTweJt1T37EhL4vTJFTJ3D9PEGfrYAsa0IFDPFiIS0FveskbHDyDeCDMDDPU3jjEEVs1lHG7Wl8lgWy3o5VF5xJ_ZI04ym6WOx0zM7wAtZpG-B95fDakxSvQJ697HBlBUoVGYz94vi',
     'width': 1280}],
   'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'plus_code': {'compound_code': 'V86W+7Q Paris, France',
    'global_code': '8FW4V86W+7Q'},
   'rating': 4.1,
   'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'scope': 'GOOGLE',
   'types': ['city_hall',
    'lodging',
    'local_government_office',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 953,
   'vicinity': '4 Rue des Innocents, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8607658, 'lng': 2.3465318},
    'viewport': {'northeast': {'lat': 48.8620584302915,
      'lng': 2.347692880291501},
     'southwest': {'lat': 48.85936046970851, 'lng': 2.344994919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Novotel Paris Les Halles',
   'photos': [{'height': 2000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111815616573299411056">Novotel Paris Les Halles</a>'],
     'photo_reference': 'AW30NDyok1AsL-BaSRo8gtqiiRROFzXo7Hk5fYeIogLRVzEC4E-nr6C-Oa4AjD8t2fKSMzu-prTPrMPBYoUkNh3GUNsJstHJKEsg1Xd0crF3Xr2PnCvptnr9fBqhZD433WzgMMJbKzgnuIslNdrUlUU0PVcSTDVFkFblGyv-ANBTdZNtQt4r',
     'width': 3000}],
   'place_id': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'plus_code': {'compound_code': 'V86W+8J Paris, France',
    'global_code': '8FW4V86W+8J'},
   'rating': 4.4,
   'reference': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2706,
   'vicinity': '8 Place Marguerite de Navarre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.860352, 'lng': 2.3440948},
    'viewport': {'northeast': {'lat': 48.86165553029149,
      'lng': 2.345549080291502},
     'southwest': {'lat': 48.8589575697085, 'lng': 2.342851119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Ducs de Bourgogne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1390,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101411638353598558320">Hôtel Ducs de Bourgogne</a>'],
     'photo_reference': 'AW30NDx6IZi1VKUgIZSHh-bWsFcShxqwK5u1eaJQRRmDneOham-QSvjhxoFiGaECXuU9_nczwoaVwlDqxMegJ5f4lVDwU2ueNrvhzX_HV38LwNjeFLLkEs_uUAaPGA59gkdoSSX3KnuSRIOKwYu-gJmdjzmTPtZKQsceaNI99nGllG7Exua3',
     'width': 2048}],
   'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'plus_code': {'compound_code': 'V86V+4J Paris, France',
    'global_code': '8FW4V86V+4J'},
   'rating': 4.5,
   'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 329,
   'vicinity': '19 Rue du Pont Neuf, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8555149, 'lng': 2.3408589},
    'viewport': {'northeast': {'lat': 48.8569105302915,
      'lng': 2.342311930291502},
     'southwest': {'lat': 48.8542125697085, 'lng': 2.339613969708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Saint-Germain-des-Prés Paris (Apart hotel Paris)',
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113188832595116816387">Citadines Apart&#39;hotel Saint-Germain-des-Prés Paris</a>'],
     'photo_reference': 'AW30NDz21MgiQcKC9bPOvqQmrdq0vfMFk08gCvM9rweYBzB79yzYyMNzyLBAzudJMVGzK-M3dBY2FLiQUpGD8lvxMYgrQ6HLK6QmyttaxTn8CSO1NdJmrrnsNzoxz5wJpHIp0Ocowfw2nOrsmoQIacccGfJeMumqyOGckVrG1tF9e6noRrXw',
     'width': 6720}],
   'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'plus_code': {'compound_code': 'V84R+68 Paris, France',
    'global_code': '8FW4V84R+68'},
   'rating': 4.3,
   'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'scope': 'GOOGLE',
   'types': ['city_hall',
    'lodging',
    'local_government_office',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 769,
   'vicinity': '53 ter Quai des Grands Augustins, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8524547, 'lng': 2.3472064},
    'viewport': {'northeast': {'lat': 48.8538838802915,
      'lng': 2.348601530291502},
     'southwest': {'lat': 48.8511859197085, 'lng': 2.345903569708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Esmeralda',
   'opening_hours': {'open_now': False},
   'photos': [{'height': 1960,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106443224837840180239">Fraz A. Khan</a>'],
     'photo_reference': 'AW30NDxg8pmA4D3v31dz6SUPkUMBkeSMvGanCdcNTtmJpvObsj277H5ZcCied1yStrqgBRjKyaOg4N7OkldevIxnfcinHyH-UgC08rbzqBHcGAlw5bEsfGnfbscKoZSOQWx5evwqKccnDyP2qBbRUgGX3XkWTBdi54eZULKldzuo7lt1skQ0',
     'width': 4032}],
   'place_id': 'ChIJO_g_H-Fx5kcRmaabUHA3dT4',
   'plus_code': {'compound_code': 'V82W+XV Paris, France',
    'global_code': '8FW4V82W+XV'},
   'rating': 4.1,
   'reference': 'ChIJO_g_H-Fx5kcRmaabUHA3dT4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 178,
   'vicinity': '4 Rue Saint-Julien le Pauvre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8530901, 'lng': 2.3447174},
    'viewport': {'northeast': {'lat': 48.8544535802915,
      'lng': 2.345997680291501},
     'southwest': {'lat': 48.85175561970851, 'lng': 2.343299719708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Albe Hotel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1152,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117571951379278191466">Albe Hotel Saint Michel</a>'],
     'photo_reference': 'AW30NDyEU5CcDtEx6q3SzOcA9xjPIV2MTAuyK09Z1QKjZljM0KPBfKaz3XsuQzSRW5w4gerFkVxahVB5Ev2QawYSnS6iiOTR5GjTtBH5u2c66rHB3zf-8OLJTyKvD67sBNKcs80rZGdiF8Qn0G3ZP5eO_RiT9uBaNxbxblwAdPhkcT5jNAKq',
     'width': 1600}],
   'place_id': 'ChIJ8R5-hOBx5kcRsCOdfj8GLeY',
   'plus_code': {'compound_code': 'V83V+6V Paris, France',
    'global_code': '8FW4V83V+6V'},
   'rating': 4.5,
   'reference': 'ChIJ8R5-hOBx5kcRsCOdfj8GLeY',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 401,
   'vicinity': '1 Rue de la Harpe, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8532403, 'lng': 2.3457375},
    'viewport': {'northeast': {'lat': 48.85462748029149,
      'lng': 2.347175730291502},
     'southwest': {'lat': 48.8519295197085, 'lng': 2.344477769708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Les Rives de Notre-Dame Hotel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116242575283063930652">Michael Scholz</a>'],
     'photo_reference': 'AW30NDxaCHzA0QoGPfSJIVAbtqmhS2yh-c8LTkWpFFKkudcSc2eAnnxfWpq88wlFvcwzzzhIUCNLoW6CheSDch1PxgnmqZU0bzrMCDRYFr0o5U366cBokf-zLZywnzNuoov4OElE-tRc20HQT1tctlphFyCl_lbsde7g2qIOQS7aAAATD-66',
     'width': 6048}],
   'place_id': 'ChIJl7vs8-Bx5kcRfIQzq_4_XmU',
   'plus_code': {'compound_code': 'V83W+77 Paris, France',
    'global_code': '8FW4V83W+77'},
   'rating': 4.6,
   'reference': 'ChIJl7vs8-Bx5kcRfIQzq_4_XmU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 106,
   'vicinity': '15 Quai Saint-Michel, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.85184049999999, 'lng': 2.3448082},
    'viewport': {'northeast': {'lat': 48.85313118029149,
      'lng': 2.346159280291502},
     'southwest': {'lat': 48.8504332197085, 'lng': 2.343461319708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel 4 étoiles Parc Saint-Séverin Paris 5ème - Esprit de France',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2362,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107542132357877294567">Hôtel 4 étoiles Parc Saint Séverin Paris 5ème - Esprit de France</a>'],
     'photo_reference': 'AW30NDyqX6Kn7PQIIkAErDxlAQuIPJi2T_QYjeuN_scVblv7ilbY3dizyLNRZ9zEqx5VGi3R5s4DCqi0L_B_xTcPZW2FKT-YMaMsbrY5Ko6V7GvQT4PIxlB5szltZSZhtwkTlUGniHzyfnMR9B7DNQcMhUMfNXKrz8kaNkft_cnekK19VNZ0',
     'width': 3776}],
   'place_id': 'ChIJ9--kuuBx5kcRojwQ1yEK2cY',
   'plus_code': {'compound_code': 'V82V+PW Paris, France',
    'global_code': '8FW4V82V+PW'},
   'rating': 4.6,
   'reference': 'ChIJ9--kuuBx5kcRojwQ1yEK2cY',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 199,
   'vicinity': '22 Rue de la Parcheminerie, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8518743, 'lng': 2.3463436},
    'viewport': {'northeast': {'lat': 48.8532481802915,
      'lng': 2.347596830291502},
     'southwest': {'lat': 48.8505502197085, 'lng': 2.344898869708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hotel Henri IV Rive Gauche',
   'photos': [{'height': 4032,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117561863517287206024">Muzafar Husain</a>'],
     'photo_reference': 'AW30NDyKnFQ8ayyo76b55I3tECKFa_fLVtRlQKoqvDiE7YD242BqP8e8whu_zEVqunGzdIF2tqcn-QFwcy6O73eM7GhtQT55KELiHAKa6KfojAyECR0GjXJ-2AOPHI7kXdZa9ATFTnWb2bFQXUKULR6UOJFqvU3MYKIMA3Lifnfl_Qfun6vA',
     'width': 3024}],
   'place_id': 'ChIJ2a4f2-Bx5kcR40Wl3uv_53Y',
   'plus_code': {'compound_code': 'V82W+PG Paris, France',
    'global_code': '8FW4V82W+PG'},
   'rating': 4.5,
   'reference': 'ChIJ2a4f2-Bx5kcR40Wl3uv_53Y',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 175,
   'vicinity': 'Rue Saint-Jacques, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8600866, 'lng': 2.3533543},
    'viewport': {'northeast': {'lat': 48.86148808029149,
      'lng': 2.354740780291502},
     'southwest': {'lat': 48.85879011970849, 'lng': 2.352042819708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Beaubourg',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2684,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115421447635584539926">Hôtel Beaubourg</a>'],
     'photo_reference': 'AW30NDydRRlgHysYhhptMf1ItGQ5Kqhgzif6QPh4Kv-lj2BiFfSrgmRBhkC_U_m_NUAptuxM1q1bOPEvs-IfUraikoBhk8Y3NJke05exYVIJHoi2oWltkeijZ5ZdnnT1A_r0TT9otHunUdOfXOOWM1DTPwradBTqpLvBgEPMtosOgy2T42p0',
     'width': 5937}],
   'place_id': 'ChIJCdHKjhxu5kcR0YtyGr7Vftc',
   'plus_code': {'compound_code': 'V963+28 Paris, France',
    'global_code': '8FW4V963+28'},
   'rating': 4.2,
   'reference': 'ChIJCdHKjhxu5kcR0YtyGr7Vftc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 170,
   'vicinity': '11 Rue Simon le Franc, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.859876, 'lng': 2.347049},
    'viewport': {'northeast': {'lat': 48.8610872802915,
      'lng': 2.348425880291502},
     'southwest': {'lat': 48.8583893197085, 'lng': 2.345727919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': "Hôtel Des Ducs D'Anjou",
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1400,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115209143941459061727">Hotel Des Ducs D&#39;Anjou</a>'],
     'photo_reference': 'AW30NDwAexa_0zWghcIee-cL6ajQfavs6pIX-pVtWfRED14hlW07h_2qvlYVAeC-u5gvTj9dYjfCBCVqvs1hBv6kCR-m84NxAIMEoGAiYwWbe-dDCPrlDPEtLPmtUwtfu7XimMj-TT96Oic9CT2uqc25ZddxMf_zW8IeKj17bFK44leBvgIZ',
     'width': 1352}],
   'place_id': 'ChIJ9ekWGR9u5kcRsS8j5TnWeSE',
   'plus_code': {'compound_code': 'V85W+XR Paris, France',
    'global_code': '8FW4V85W+XR'},
   'rating': 3.9,
   'reference': 'ChIJ9ekWGR9u5kcRsS8j5TnWeSE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 345,
   'vicinity': '1 Rue Sainte-Opportune, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8515237, 'lng': 2.3486679},
    'viewport': {'northeast': {'lat': 48.8529256302915,
      'lng': 2.349962130291502},
     'southwest': {'lat': 48.8502276697085, 'lng': 2.347264169708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Maison Colbert Member of Meliá Collection',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3656,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102194778927204133336">Hotel Maison Colbert Member of Meliá Collection</a>'],
     'photo_reference': 'AW30NDxEg7u7RPADrkyflDOToh7Pz-9UM_tlpnNah2TE6yBGGo-2UOR3yTtmHJmJePAZQC5hGGYfiKzamwsPbZSEjEI4HE6rDRRnXqAUVTLVANceyQ_kA6vWNwqDaTDQtP308i5Xqq_IIARsqmrtAFfuYL5RXDk0e747HVNG1jfl9CbsRSJG',
     'width': 3543}],
   'place_id': 'ChIJI3vbSOFx5kcR84E4IeL2LqI',
   'plus_code': {'compound_code': 'V82X+JF Paris, France',
    'global_code': '8FW4V82X+JF'},
   'rating': 4.7,
   'reference': 'ChIJI3vbSOFx5kcR84E4IeL2LqI',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 31,
   'vicinity': "7 Rue de l'Hôtel Colbert, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8499446, 'lng': 2.346247699999999},
    'viewport': {'northeast': {'lat': 48.8513264802915,
      'lng': 2.347622530291501},
     'southwest': {'lat': 48.8486285197085, 'lng': 2.344924569708497}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Home Latin',
   'photos': [{'height': 4080,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113966656287531023757">Ioan Mihael</a>'],

In [27]:
len(hotels["results"])

20

In [28]:
# Iterate Through hotel_df DataFrame

In [29]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError): 
        print("Hotel not found..... skipping.")

Hotel not found..... skipping.
Hotel not found..... skipping.
Hotel not found..... skipping.
Hotel not found..... skipping.
Hotel not found..... skipping.
Hotel not found..... skipping.
Hotel not found..... skipping.
Hotel not found..... skipping.

In [32]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
2,Pedernales,DO,78.40,18.0384,-71.7440,Hotel Costa Marina
3,Atuona,PF,77.79,-9.8000,-139.0333,Villa Enata
4,Butaritari,KI,81.50,3.0707,172.7902,Isles Sunset Lodge
5,Samarai,PG,82.22,-10.6167,150.6667,Nuli Sapi
7,Carutapera,BR,76.33,-1.1950,-46.0200,Lidera
12,Marawi,PH,76.95,7.9986,124.2928,Derogongan Residence
13,Salalah,OM,84.29,17.0151,54.0924,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
15,Cockburn Town,TC,81.79,21.4612,-71.1419,Osprey Beach Hotel
19,Saint-Louis,SN,77.38,16.3333,-15.0000,
20,Souillac,MU,80.98,-20.5167,57.5167,Shanti Maurice Resort & Spa

In [34]:
# Create a Maximum Temperature Heatmap from a Hotel DataFrame

In [35]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [36]:
# Add a heatmap of temperature for the vacation spots and MARKER for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [37]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [38]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))